name: Run Tests

# Trigger the action on pushes and pull requests to the main branch
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

# Define the jobs that will run as part of this workflow
jobs:
  test:
    runs-on: ubuntu-latest  # The environment where the tests will run
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v3  # Set up the Python environment
        with:
          python-version: '3.x'  # Specify the Python version, e.g., '3.12'
      - name: Install dependencies
        run: |
          cd recomendations_etl
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          make test